Improve description for schedule_expression
spacelift-io/terraform-aws-spacelift-workerpool-on-ec2 pull request #55
Opened 2023-10-10 06:04 UTC by alexjurkiewicz

## Description of the change

> Description here

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue);
- [ ] New feature (non-breaking change that adds functionality);
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected);
- [ ] Documentation (a documentation or example fix not affecting the infrastructure managed by this module);

## Checklists

### Development

- [ ] All necessary variables have been defined, with defaults if applicable;
- [ ] The code is formatted properly;

### Code review

- [ ] The module version is bumped accordingly;
- [ ] Spacelift tests are passing;
- [ ] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached;
- [ ] This pull request is no longer marked as "draft";
- [ ] Reviewers have been assigned;
- [ ] Changes have been reviewed by at least one other engineer;

2023-10-19 13:14 UTC, jmfontaine approved these changes

2023-10-23 13:26 UTC, eminalemdar requested changes
since this PR is changing the variables, the docs section should be updated as well. can you please check out [this](https://github.com/spacelift-io/terraform-aws-spacelift-workerpool-on-ec2#how-to-generate-docs) section on that

2023-10-31 06:50 UTC, alexjurkiewicz commented
I've updated the docs 🙏

2023-11-03 11:22 UTC, adamconnelly approved these changes
Looks good - thanks for that!

2023-11-03 11:22 UTC, merged