Make Lambda function instruction set architecture variable
spacelift-io/terraform-aws-spacelift-workerpool-on-ec2 pull request #60
Opened 2023-10-17 14:00 UTC by jeohist

## Description of the change

> [ec2-workerpool-scheduler](https://github.com/spacelift-io/ec2-workerpool-autoscaler) releases an amd64 and arm64 version.
> By adding a variable to this module, users are given the choice which one they'd like to use.
> amd64 was chosen as the default as this was previously the case.

## Type of change

- [X] New feature (non-breaking change that adds functionality);

## Checklists

### Development

- [X] All necessary variables have been defined, with defaults if applicable;
- [X] The code is formatted properly;

### Code review

- [ ] The module version is bumped accordingly;
- [ ] Spacelift tests are passing;
- [ ] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached;
- [ ] This pull request is no longer marked as "draft";
- [ ] Reviewers have been assigned;
- [ ] Changes have been reviewed by at least one other engineer;

2023-10-19 13:23 UTC, jmfontaine approved these changes
Good idea. Thanks for the contribution!

2023-10-23 13:31 UTC, eminalemdar requested changes
to be able to introduce these changes the module version should be bumped as well both in the config and the documentation section. can you please also update those?

2023-11-21 18:09 UTC, jeohist commented
> to be able to introduce these changes the module version should be bumped as well both in the config and the documentation section. can you please also update those?

I've rebased the MR and updated the module version referenced with a patch update.

2023-11-22 07:24 UTC, eminalemdar requested changes

2023-11-22 07:24 UTC, eminalemdar commented on .spacelift/config.yml
> +module_version: 2.1.1
This change is introducing a new functionality and I think updating the minor version would be more appropriate. Thank you!

```suggestion
module_version: 2.2.0
```

2023-11-22 07:24 UTC, eminalemdar commented on README.md
> +  source = "github.com/spacelift-io/terraform-aws-spacelift-workerpool-on-ec2?ref=v2.1.1"
This change is introducing a new functionality and I think updating the minor version would be more appropriate. Thank you!

```suggestion
  source = "github.com/spacelift-io/terraform-aws-spacelift-workerpool-on-ec2?ref=v2.2.0"
```

2023-11-22 13:13 UTC, eminalemdar approved these changes
LGTM! Thank you for your contribution @jeohist

2023-11-22 13:33 UTC, merged