Prevents persistent diff with option to deploy lambda from s3 package
spacelift-io/terraform-aws-spacelift-workerpool-on-ec2 pull request #83
Opened 2024-01-30 23:21 UTC by lorengordon

## Description of the change

This pr introduces new, optional inputs that allow the user to specify the s3 package options for the autoscaler lambda. With this pr, it is up to the user to host the autoscaler lambda in their own s3 bucket. See the example for the general setup. This configuration prevents the persistent diff that currently occurs when setting `enable_autoscaling = true`. 

Fixes #82 

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue);
- [x] New feature (non-breaking change that adds functionality);
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected);
- [x] Documentation (a documentation or example fix not affecting the infrastructure managed by this module);

## Checklists

### Development

- [x] All necessary variables have been defined, with defaults if applicable;
- [x] The code is formatted properly;

### Code review

- [ ] The module version is bumped accordingly;
- [ ] Spacelift tests are passing;
- [ ] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached;
- [ ] This pull request is no longer marked as "draft";
- [ ] Reviewers have been assigned;
- [ ] Changes have been reviewed by at least one other engineer;

2024-02-06 18:57 UTC, lorengordon commented
I did some work to see if we could use a data source for `aws_s3_object` to retrieve the checksum and use that for change detection, but it turns out that the `checkum_sha256` of the s3 object is not compatible with the `source_code_hash` input of the lambda resource. Unfortunately, the s3 object checksum is based on all the parts of the upload, and not the final checksum of the object itself.

Instead the s3 object will need a unique key for every update, or object versioning, in order for the lambda resource to perform change detection and update the package on any change.

2024-02-26 17:35 UTC, lorengordon commented
@eminalemdar Just wanted to check in on this PR and see if you had any further feedback. I've been using the approach in my fork of this project, and its been working well... Thanks!

2024-03-08 07:55 UTC, eminalemdar requested changes
@lorengordon Thank you for the contributions. I've requested some changes

2024-03-08 07:55 UTC, eminalemdar commented on examples/autoscaler-s3-package/variables.tf
you can leave the values of these variables as empty because these variable values can be defined in the test config file.

2024-03-08 07:55 UTC, eminalemdar commented on .spacelift/config.yml
Module version should be bumped in order to introduce these changes

2024-03-08 07:55 UTC, eminalemdar commented on README.md
Module version should be bumped in the example provided in this file in order to introduce these changes.

2024-03-11 18:38 UTC, lorengordon commented on .spacelift/config.yml
done

2024-03-11 18:38 UTC, lorengordon commented on README.md
done

2024-03-11 18:38 UTC, lorengordon commented on examples/autoscaler-s3-package/variables.tf
done

2024-03-11 18:39 UTC, lorengordon commented
@eminalemdar Thanks for the review, I went ahead and made the requested changes.

2024-03-14 13:58 UTC, jmfontaine approved these changes
Looks good to me 👍 

Thanks for your contribution @lorengordon!

2024-03-15 20:01 UTC, eminalemdar approved these changes

2024-03-15 20:03 UTC, eminalemdar commented
@lorengordon thank you for the contribution!

2024-03-15 20:04 UTC, merged